// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;


public class TestySelenium {

    private WebDriver driver;


    // Tag Before oznacza ze metoda setUp () wykona sie przed testem
    @Before
    public void setUp() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();

    }

    // quit () - wychodzenie z przegladarki
    // taka metoda powinna byc zawsze byc na koncu kazdego testu
    // Tag After oznacza ze wykona sie po tescie
    @After
    public void tearDown() {
        driver.quit();
    }


    @Test
    public void dodanieTekstuDoInitial() throws InterruptedException {
        // metoda get otwiera nam strone internetowa
        driver.get("http://executeautomation.com/demosite/index.html");
        // do wyszukiwania elementow sluzy metoda findElement
        WebElement initial = driver.findElement(By.id("Initial"));
        // sendKeys wstawia elementy do textBoxa
        initial.sendKeys("Imie");
        Thread.sleep(3000);
    }

    @Test
    public void wstawImieINazwisko() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html#");
        // krok 1 wstaw tekst do First Name
        WebElement imie = driver.findElement(By.id("FirstName"));
        imie.sendKeys("Imie");
        Thread.sleep(3000);
        //krok 2 wstaw tekst do Middle Name
        WebElement nazwisko = driver.findElement(By.id("MiddleName"));
        nazwisko.sendKeys("Nazwisko");
        Thread.sleep(3000);
    }

    @Test
    public void zaznaczCheckbox() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html#");
        // krok 1 odznacz checkbox english
        WebElement checkboxEnglish = driver.findElement(By.name("english"));
        checkboxEnglish.click();
        Thread.sleep(3000);
        // krok2 zaznacz checkbox hindi
        // szukamy elementu hindi checkbox
        WebElement checkboxHindi = driver.findElement(By.name("Hindi"));
        // zaznaczamy checkbox Hindi
        checkboxHindi.click();

    }

    @Test
    public void wstawUsername() throws InterruptedException {
        driver.get("http://newtours.demoaut.com/index.php");
        WebElement userName = driver.findElement(By.name("userName"));
        userName.sendKeys("Ola");
        Thread.sleep(3000);
    }

    @Ignore
    @Test
    public void wstawPassword() throws InterruptedException {
        driver.get("http://newtours.demoaut.com/index.php");
        WebElement password = driver.findElement(By.name("password"));
        password.sendKeys("test");
        Thread.sleep(3000);


    }

    @Ignore
    @Test
    public void dropdown() throws InterruptedException {
        //dropdown - rozwijana lista
        // dropdown = select
        driver.get("http://executeautomation.com/demosite/index.html");
        // poloczenie
        Select dropdown = new Select(driver.findElement(By.id("TitleId")));
        //dropdpwn.selectByVisibleText("Mr.");
        // dropdown.selectByIndex(1);

        dropdown.selectByValue("1");
        Thread.sleep(3000);
    }



    @Test
    public void wielokrotnyWybor() throws InterruptedException {
        driver.get("http://output.jsbin.com/osebed/2");
        Select wybierz = new Select(driver.findElement(By.id("fruits")));
        wybierz.selectByValue("apple");
        Thread.sleep(3000);
        wybierz.selectByVisibleText("Banana");
        Thread.sleep(3000);

    }



    @Test
    public void linkText() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        WebElement linkText = driver.findElement(By.linkText("HtmlPopup"));
        //kliknij w element
        linkText.click();
        Thread.sleep(3000);


    }

    @Ignore
    @Test
    public void partialLink() throws InterruptedException {
        driver.get("http://newtours.demoaut.com/index.php");
        //tworzymy element partial link
        WebElement partialLink = driver.findElement(By.partialLinkText("SIGN"));
        // klikamy w partial link
        partialLink.click();
        Thread.sleep(3000);
    }

    @Ignore
    @Test
    public void alertAccepted() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        // musimy stworzyc element dla buttona Generate
        WebElement buttonGenerate = driver.findElement(By.name("generate"));
        // klikamy na button
        buttonGenerate.click();
        Thread.sleep(3000);

        // musimy sie przelaczyc na alert
        Alert alertElement = driver.switchTo().alert();
        // chcemy kliknac ok na alaercie
        alertElement.accept();
        // chcemy zaakceptowac nastepnego alerta
        alertElement.accept();
        Thread.sleep(3000);

    }

    @Ignore
    @Test
    public void alertDismiss() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        // musimy stworzyc element dla buttona Generate
        WebElement buttonGenerate = driver.findElement(By.name("generate"));
        // klikamy na button
        buttonGenerate.click();
        Thread.sleep(3000);

        // musimy sie przelaczyc na alert
        Alert alertElement = driver.switchTo().alert();
        // chcemy kliknac ok na alaercie
        alertElement.dismiss();
        // chcemy zaakceptowac nastepnego alerta
        alertElement.accept();
        Thread.sleep(3000);
    }

    @Test
    public void radioButtony() throws InterruptedException {
        driver.get("http://demo.guru99.com/test/radio.html");
        // stworzymy 3 elementy (radio buttony)
        WebElement radio1 = driver.findElement(By.id("vfb-7-1"));
        WebElement radio2 = driver.findElement(By.id("vfb-7-2"));
        WebElement radio3 = driver.findElement(By.id("vfb-7-3"));
        radio3.click();
        Thread.sleep(3000);
        radio2.click();
        Thread.sleep(3000);
    }

    @Test
    public void wyszyscOkno() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        // stworz 2 elementy dla Initial i First Name
        WebElement initial = driver.findElement(By.id("Initial"));
        WebElement firstName = driver.findElement(By.id("FirstName"));
        // wstaw tekst do tych dwoch elementow
        initial.sendKeys("Test");
        firstName.sendKeys("Test");
        Thread.sleep(3000);
        // wyczysc te dwa textBoxy
        initial.clear();
        firstName.clear();
        Thread.sleep(3000);

    }

}